mongofiles -d crowdsciencemapper delete C:\Windows\Temp\php26AE.tmp     
mongofiles -d crowdsciencemapper delete C:\Windows\Temp\phpE9EE.tmp     
mongofiles -d crowdsciencemapper delete C:\Windows\Temp\php6362.tmp     
mongofiles -d crowdsciencemapper delete C:\Windows\Temp\php203C.tmp     
mongofiles -d crowdsciencemapper delete C:\Windows\Temp\php3F70.tmp     
mongofiles -d crowdsciencemapper delete C:\Windows\Temp\php76C6.tmp     
mongofiles -d crowdsciencemapper delete C:\Windows\Temp\phpC583.tmp     
mongofiles -d crowdsciencemapper delete C:\Windows\Temp\php4C6F.tmp     
mongofiles -d crowdsciencemapper delete C:\Windows\Temp\php4CCE.tmp     
mongofiles -d crowdsciencemapper delete C:\Windows\Temp\phpB255.tmp     
mongofiles -d crowdsciencemapper delete C:\Windows\Temp\phpA262.tmp     
mongofiles -d crowdsciencemapper delete C:\Windows\Temp\phpA2F0.tmp     
mongofiles -d crowdsciencemapper delete C:\Windows\Temp\phpF583.tmp     
mongofiles -d crowdsciencemapper delete C:\Windows\Temp\phpF62F.tmp     
mongofiles -d crowdsciencemapper delete C:\Windows\Temp\php1516.tmp     
mongofiles -d crowdsciencemapper delete C:\Windows\Temp\php1594.tmp     
mongofiles -d crowdsciencemapper delete C:\Windows\Temp\phpE61C.tmp     
mongofiles -d crowdsciencemapper delete C:\Windows\Temp\phpE6AA.tmp     
mongofiles -d crowdsciencemapper delete C:\Windows\Temp\php2B96.tmp     
mongofiles -d crowdsciencemapper delete C:\Windows\Temp\php3F1E.tmp     
mongofiles -d crowdsciencemapper delete C:\Windows\Temp\php4872.tmp     
mongofiles -d crowdsciencemapper delete C:\Windows\Temp\php6E7A.tmp     
mongofiles -d crowdsciencemapper delete C:\Windows\Temp\php2970.tmp     
mongofiles -d crowdsciencemapper delete C:\Windows\Temp\php2971.tmp     
mongofiles -d crowdsciencemapper delete C:\Windows\Temp\php3322.tmp     
mongofiles -d crowdsciencemapper delete C:\Windows\Temp\php33BF.tmp     
mongofiles -d crowdsciencemapper delete C:\Windows\Temp\php4B56.tmp     
mongofiles -d crowdsciencemapper delete C:\Windows\Temp\php4BF3.tmp     
mongofiles -d crowdsciencemapper delete C:\Windows\Temp\phpF7BC.tmp     
mongofiles -d crowdsciencemapper delete C:\Windows\Temp\php1433.tmp     
mongofiles -d crowdsciencemapper delete C:\Windows\Temp\php1C30.tmp     
mongofiles -d crowdsciencemapper delete C:\Windows\Temp\php307B.tmp     
mongofiles -d crowdsciencemapper delete C:\Windows\Temp\phpAD59.tmp     
mongofiles -d crowdsciencemapper delete C:\Windows\Temp\phpF2D3.tmp     
mongofiles -d crowdsciencemapper delete C:\Windows\Temp\phpF2C2.tmp     
mongofiles -d crowdsciencemapper delete C:\Windows\Temp\phpF2E4.tmp     
mongofiles -d crowdsciencemapper delete C:\Windows\Temp\phpEF9A.tmp     
mongofiles -d crowdsciencemapper delete C:\Windows\Temp\php6815.tmp     
mongofiles -d crowdsciencemapper delete C:\Windows\Temp\phpB52C.tmp     
mongofiles -d crowdsciencemapper delete C:\Windows\Temp\php7FAC.tmp     
mongofiles -d crowdsciencemapper delete C:\Windows\Temp\phpAD9F.tmp     
mongofiles -d crowdsciencemapper delete C:\Windows\Temp\php88C.tmp      
mongofiles -d crowdsciencemapper delete C:\Windows\Temp\php14BD.tmp     
mongofiles -d crowdsciencemapper delete C:\Windows\Temp\php1B24.tmp     
mongofiles -d crowdsciencemapper delete C:\Windows\Temp\php4502.tmp     
mongofiles -d crowdsciencemapper delete C:\Windows\Temp\php7AF1.tmp     
mongofiles -d crowdsciencemapper delete C:\Windows\Temp\php8619.tmp     
mongofiles -d crowdsciencemapper delete C:\Windows\Temp\php52AC.tmp     
mongofiles -d crowdsciencemapper delete C:\Windows\Temp\php9DFE.tmp     
mongofiles -d crowdsciencemapper delete C:\Windows\Temp\phpAA2F.tmp     
mongofiles -d crowdsciencemapper delete C:\Windows\Temp\phpA753.tmp     
mongofiles -d crowdsciencemapper delete C:\Windows\Temp\phpD97B.tmp     
mongofiles -d crowdsciencemapper delete C:\Windows\Temp\php2599.tmp     
mongofiles -d crowdsciencemapper delete C:\Windows\Temp\phpC504.tmp     
mongofiles -d crowdsciencemapper delete C:\Windows\Temp\phpF68F.tmp     
mongofiles -d crowdsciencemapper delete C:\Windows\Temp\php4A4B.tmp     
mongofiles -d crowdsciencemapper delete C:\Windows\Temp\php8597.tmp     
mongofiles -d crowdsciencemapper delete C:\Windows\Temp\php26A7.tmp     
mongofiles -d crowdsciencemapper delete C:\Windows\Temp\php50D3.tmp     
mongofiles -d crowdsciencemapper delete C:\Windows\Temp\phpAE5E.tmp     
mongofiles -d crowdsciencemapper delete C:\Windows\Temp\phpE161.tmp     
mongofiles -d crowdsciencemapper delete C:\Windows\Temp\php992C.tmp     
mongofiles -d crowdsciencemapper delete C:\Windows\Temp\phpD800.tmp     
mongofiles -d crowdsciencemapper delete C:\Windows\Temp\phpF541.tmp     
mongofiles -d crowdsciencemapper delete C:\Windows\Temp\php267F.tmp     
